### ISSUE TITLE
Use delayed binding to create expensive functions

### ISSUE THREAD

**Issue by hadley** [tidyverse/design#108]
Because they're run once 

Use for backports etc

**Comment by jimhester** [comment]
There isn't really enough detail here for me to be sure what you are talking about. But if it is `delayedAssign()` this is such a rarely needed technique I am not sure it is worth addressing in a general design document...

**Comment by hadley** [comment]
I was thinking specifically for packages, instead of initialising to `NULL` and then rebinding inside of `.onLoad()`

**Comment by hadley** [comment]
We now also have `rlang::on_load()`, so I no longer think we need this issue.
