### ISSUE TITLE
Update Status in Welcome?

### ISSUE THREAD

**Issue by jonthegeek** [tidyverse/design#133]
From the [Welcome](https://design.tidyverse.org/index.html):

> This book will be under heavy development for quite some time; currently we are loosely aiming for completion in 2020. You’ll find many chapters contain disjointed text that mostly serve as placeholders for the authors, and I do not recommend attempting to systematically read the book at this time.

So far I'm finding this to be super useful, even if it perhaps isn't done. Only a couple chapters ([Vectorisation](https://design.tidyverse.org/out-vectorisation.html) and [Error call](https://design.tidyverse.org/err-call.html)) and the [glossary](https://design.tidyverse.org/glossary.html) appear like maybe they're shorter than intended, even if some things aren't perfect, 

I've had some questions at R4DS about learning more design-principle-like things for function/package writing (vs nuts and bolts like Advanced R and R Packages), and this looks to be the resource people are looking for (as am I).

Perhaps something like:

> As of 2022, this book is not complete. You may find that some topics go into less detail than you would like, or that a tip is confusing or even contradictory. We hope that you still find it helpful, and welcome contributions to the continued development of this book via GitHub.

I'm imaging that "GitHub" would link to a CONTRIBUTING.md.

**Comment by batpigandme** [comment]
Re. the proposed intro change with:

> We hope that you still find it helpful, and welcome contributions to the continued development of this book via GitHub.

I think we want to be sure that latter part is true before stating it. It's not that it's UN-true, but, thus far, this “book” has reflected somewhat opinionated design principles implemented across tidyverse packages, which isn't particularly “contribution” friendly.  There have been PRs fixing typos or streamlining the wording, but, to me “welcom[ing] contributuon to the continued development of this book” implies something beyond that.

**Comment by jonthegeek** [comment]
Yeah, I figured there might be some... massaging of that language. And the CONTRIBUTING.md would lay out exactly what's welcomed vs what might require a discussion, in any case. Probably something aimed more at inviting issues and/or discussions (in that sentence in the text itself)?

My thought was that it would probably clean up faster if the crowd points out things that are clear to the team but foggy to outsiders.

**Comment by wurli** [comment]
I'd also like to advocate for an update to the Welcome section. I often point others to the Tidyverse design guide (it's a great resource!), but currently I worry that the landing page for the site is a bit misleading. Particularly the line 'currently we are loosely aiming for completion in 2020' suggests that this is an outdated resource.
