### ISSUE TITLE
Documentation: Guidance on combining function help?

### ISSUE THREAD

**Issue by ateucher** [tidyverse/design#139]
At workweek we heard that sometimes users are surprised and/or overwhelmed when they type `?fun` and get a help page that doesn't look like what they were expecting, because it includes many other functions and/or is a topic more general than they were expecting.

Would a section providing guidance on when to bundle help topics and when to keep them separate (e.g., use of `@inherit*` vs `@rdname` or `@describeIn`, or use of child documents) be in scope for this guide?

**Comment by hadley** [comment]
I _think_ this is out of scope because we want to stay focussed pretty closely on topics related to writing functions. It's possible I'll reconsider this later, but there's already a lot of ground to cover.
