### ISSUE TITLE
Consider using discussions for discussions?

### ISSUE THREAD

**Issue by TimTaylor** [tidyverse/design#153]
Would it be worth using [GitHub discussions](https://docs.github.com/discussions) for design discussions? Appreciate you've also got substack to monitor but having some here as well would also fit nicely with where book development occurs.

**Comment by hadley** [comment]
There are already slightly too many venues for discussion (on substack, people replying to the emails, on linkedin, and on fosstodon), so I think adding one more would be challenging for me.
