### ISSUE TITLE
Environment variables vs options

### ISSUE THREAD

**Issue by olivroy** [tidyverse/design#166]
I see that many tidyverse packages use environment variables or options, sometimes interchangeably ?

If I look at cli for example?
https://cli.r-lib.org/reference/cli-config.html?q=config#user-facing-configuration

So I think a section on env variable vs options could be useful?

I tried scanning advanced R, but couldn't find reference on the subject.

**Comment by hadley** [comment]
See #65 for where we're tracking this.
