### ISSUE TITLE
Fix names.Rmd

### ISSUE THREAD

**Issue by jennybc** [tidyverse/design#96]
The `names.Rmd` section doesn't render now that `tibble:::set_minimal_names(x)` no longer exists. It's used like so:

````

Consider an unnamed vector, i.e. it has names attribute of `NULL`.

```{r}
x <- letters[1:3]
names(x)
```

Repair the names to make them minimal.

```{r}
x <- tibble:::set_minimal_names(x)
names(x)
```
````

Where does this sort of function live now and what's it called?

cc @lionel- @krlmlr

**Comment by krlmlr** [comment]
I'm not sure we already have a replacement? Is the user supposed to do

```r
names(x) <- vec_as_names(names(x))
```

or do we offer a more comfortable solution?

**Comment by jennybc** [comment]
Another function that went missing that was called in this exposition is `tibble:::unique_names()`.

**Comment by lionel-** [comment]
We've deliberately kept the API to a minimum, so we don't have to solve the columns / rows conundrum in vctrs right away. A vctrs function would normally repair the row names of data frames, which isn't as useful as repairing the column names.

**Comment by jennybc** [comment]
I see. Without offering a concrete solution, I'll just observe it would be nice to eventually get some `set_names` functionality. It's especially important for talking about minimal names, because they are the one level of naminess that can't be described in a "names in, names out" way. If `names` atttribute is `NULL`, you need to consult the size of the object to learn how many names are needed.
