### ISSUE TITLE
.name_repair defaults.

### ISSUE THREAD

**Issue by nickbond** [tidyverse/design#97]
I know it's been discussed previously, but I find default names from `janitor::make_clean_names` to be much more readable and consistent in their style with other naming conventions.

I currently default to including `.name_repair = janitor::make_clean_names` when using `.name_repair`, however, it would be great to have something similar to `make_clean_names` among the default options for the `name_repair` function.

Thanks as always for a great set of tools.

**Comment by hadley** [comment]
I think you might have filed this in the wrong repo.
